(set-face-attribute 'default nil :font "DejaVu Sans Mono" :height 110 :foreground "#fdf4c1" :background "#282828")
(set-face-attribute 'cursor t :background "#fdf4c1")
(set-face-attribute 'highlight t :background "#333333")
(set-face-attribute 'fringe t :background "#282828")
(set-face-attribute 'mode-line t :foreground "#262626" :background "#FE8019")
(set-face-attribute 'region t :background "#504945")
(set-face-attribute 'secondary-selection t :background "#3e3834")
(set-face-attribute 'font-lock-builtin-face t :foreground "#fe8019")
(set-face-attribute 'font-lock-comment-face t :foreground "#7c6f64")
(set-face-attribute 'font-lock-function-name-face t :foreground "#a99865")
(set-face-attribute 'font-lock-keyword-face t :foreground "#dd6f48")
(set-face-attribute 'font-lock-string-face t :foreground "#429489")
(set-face-attribute 'font-lock-type-face t :foreground "#66999d")
(set-face-attribute 'font-lock-constant-face t :foreground "#bbaa97")
(set-face-attribute 'font-lock-variable-name-face t :foreground "#83a598")
(set-face-attribute 'minibuffer-prompt t :foreground "#75b45c" :bold t)
(set-face-attribute 'font-lock-warning-face t :foreground "#ff0000" :bold t)
